package com.bt.nat.item;

// default package
// Generated 14-Feb-2014 15:30:39 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TEsitestItems generated by hbm2java
 */
@Entity
@Table(name = "t_esitest_items")
@NamedQuery(name = TEsitestItems.FIND_BY_EIN, query = "select a from TEsitestItems a where a.teiEngineerEin = :ein")
public class TEsitestItems implements java.io.Serializable {

	public static final String FIND_BY_EIN = "TEsitestItems.findByEin";

	private long teiId;
	private Integer teiEngineerEin;
	private String teiEngineerEinOld;
	private String teiOldEin;
	private String teiItemSerial;
	private TEsitestItemMaster teiMaster;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tei_tim_id", columnDefinition = "bigint")
	public TEsitestItemMaster getTeiMaster() {
		return teiMaster;
	}

	public void setTeiMaster(TEsitestItemMaster teiMaster) {
		this.teiMaster = teiMaster;
	}

	private TEsitestItemStatus itemStatus;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tei_tis_item_status_id")
	public TEsitestItemStatus getItemStatus() {
		return itemStatus;
	}

	public void setItemStatus(TEsitestItemStatus itemStatus) {
		this.itemStatus = itemStatus;
	}

	private Date teiNextCheckDate;
	private Date teiLastCheckDate;
	private String teiRemarks;
	private Date teiDateOfAdd;
	private String teiIsBuilding;
	private Integer teiTebId;
	private String teiItemStatusText;

	public TEsitestItems() {
	}

	public TEsitestItems(long teiId) {
		this.teiId = teiId;
	}

	public TEsitestItems(long teiId, Integer teiEngineerEin,
			String teiEngineerEinOld, String teiOldEin, String teiItemSerial,
			Date teiNextCheckDate, Date teiLastCheckDate, String teiRemarks,
			Date teiDateOfAdd, String teiIsBuilding, Integer teiTebId,
			String teiItemStatusText) {
		this.teiId = teiId;
		this.teiEngineerEin = teiEngineerEin;
		this.teiEngineerEinOld = teiEngineerEinOld;
		this.teiOldEin = teiOldEin;
		this.teiItemSerial = teiItemSerial;
		this.teiNextCheckDate = teiNextCheckDate;
		this.teiLastCheckDate = teiLastCheckDate;
		this.teiRemarks = teiRemarks;
		this.teiDateOfAdd = teiDateOfAdd;
		this.teiIsBuilding = teiIsBuilding;
		this.teiTebId = teiTebId;
		this.teiItemStatusText = teiItemStatusText;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "tei_id", unique = true, nullable = false)
	public long getTeiId() {
		return this.teiId;
	}

	public void setTeiId(long teiId) {
		this.teiId = teiId;
	}

	@Column(name = "tei_engineer_ein")
	public Integer getTeiEngineerEin() {
		return this.teiEngineerEin;
	}

	public void setTeiEngineerEin(Integer teiEngineerEin) {
		this.teiEngineerEin = teiEngineerEin;
	}

	@Column(name = "tei_engineer_ein_old", length = 11)
	public String getTeiEngineerEinOld() {
		return this.teiEngineerEinOld;
	}

	public void setTeiEngineerEinOld(String teiEngineerEinOld) {
		this.teiEngineerEinOld = teiEngineerEinOld;
	}

	@Column(name = "tei_old_ein", length = 11)
	public String getTeiOldEin() {
		return this.teiOldEin;
	}

	public void setTeiOldEin(String teiOldEin) {
		this.teiOldEin = teiOldEin;
	}

	@Column(name = "tei_item_serial", length = 50)
	public String getTeiItemSerial() {
		return this.teiItemSerial;
	}

	public void setTeiItemSerial(String teiItemSerial) {
		this.teiItemSerial = teiItemSerial;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tei_next_check_date", length = 23)
	public Date getTeiNextCheckDate() {
		return this.teiNextCheckDate;
	}

	public void setTeiNextCheckDate(Date teiNextCheckDate) {
		this.teiNextCheckDate = teiNextCheckDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tei_last_check_date", length = 23)
	public Date getTeiLastCheckDate() {
		return this.teiLastCheckDate;
	}

	public void setTeiLastCheckDate(Date teiLastCheckDate) {
		this.teiLastCheckDate = teiLastCheckDate;
	}

	@Column(name = "tei_remarks")
	public String getTeiRemarks() {
		return this.teiRemarks;
	}

	public void setTeiRemarks(String teiRemarks) {
		this.teiRemarks = teiRemarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tei_date_of_add", length = 23)
	public Date getTeiDateOfAdd() {
		return this.teiDateOfAdd;
	}

	public void setTeiDateOfAdd(Date teiDateOfAdd) {
		this.teiDateOfAdd = teiDateOfAdd;
	}

	@Column(name = "tei_is_building", length = 1)
	public String getTeiIsBuilding() {
		return this.teiIsBuilding;
	}

	public void setTeiIsBuilding(String teiIsBuilding) {
		this.teiIsBuilding = teiIsBuilding;
	}

	@Column(name = "tei_teb_id")
	public Integer getTeiTebId() {
		return this.teiTebId;
	}

	public void setTeiTebId(Integer teiTebId) {
		this.teiTebId = teiTebId;
	}

	@Column(name = "tei_item_status_text", length = 50)
	public String getTeiItemStatusText() {
		return this.teiItemStatusText;
	}

	public void setTeiItemStatusText(String teiItemStatusText) {
		this.teiItemStatusText = teiItemStatusText;
	}

}
