package com.bt.nat.item;
// default package
// Generated 14-Feb-2014 15:30:39 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TEsitestItemTestingDetails generated by hbm2java
 */
@Entity
@Table(name = "t_esitest_item_testing_details")
public class TEsitestItemTestingDetails implements java.io.Serializable {

	private TEsitestItemTestingDetailsId id;

	public TEsitestItemTestingDetails() {
	}

	public TEsitestItemTestingDetails(TEsitestItemTestingDetailsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "itdId", column = @Column(name = "itd_id", nullable = false)),
			@AttributeOverride(name = "itdTeiId", column = @Column(name = "itd_tei_id")),
			@AttributeOverride(name = "itdTestingStatus", column = @Column(name = "itd_testing_status", length = 1)),
			@AttributeOverride(name = "itdTestingDate", column = @Column(name = "itd_testing_date", length = 23)),
			@AttributeOverride(name = "itdEsiId", column = @Column(name = "itd_esi_id")),
			@AttributeOverride(name = "itdTestedByEin", column = @Column(name = "itd_tested_by_ein")) })
	public TEsitestItemTestingDetailsId getId() {
		return this.id;
	}

	public void setId(TEsitestItemTestingDetailsId id) {
		this.id = id;
	}

}
