package com.bt.nat.item;

// default package
// Generated 14-Feb-2014 15:30:39 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * TEsitestItemMaster generated by hbm2java
 */
@Entity
@Table(name = "t_esitest_item_master")
@NamedQuery(name = TEsitestItemMaster.FIND_ALL, query = "select a from TEsitestItemMaster a")
public class TEsitestItemMaster implements java.io.Serializable {

	public static final String FIND_ALL = "TEsitestItemMaster.findAll";

	private int timId;
	private String timItemName;
	private String timItemCode;
	private String timCheckType;
	private Integer timCheckPeriod;
	private TEsitestFescCheckTypes checkTypes;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tim_fct_id")
	public TEsitestFescCheckTypes getCheckTypes() {
		return checkTypes;
	}

	public void setCheckTypes(TEsitestFescCheckTypes checkTypes) {
		this.checkTypes = checkTypes;
	}

	private Integer timTimeCost;
	private Integer timTestsPerItem;
	private Integer timRepairTime;
	private Integer timServiceTime;
	private String timPeriodicCal;
	private Integer timCalPeriod;
	private Character timIsActive;
	private String timItemPurchaseType;
	private Character timIsSpareRequired;
	private Character timIsSerialRequired;
	private String timIsBuilding;
	private String timShowScreen;

	public TEsitestItemMaster() {
	}

	public TEsitestItemMaster(int timId) {
		this.timId = timId;
	}

	public TEsitestItemMaster(int timId, String timItemName,
			String timItemCode, String timCheckType, Integer timCheckPeriod,
			Integer timTimeCost, Integer timTestsPerItem,
			Integer timRepairTime, Integer timServiceTime,
			String timPeriodicCal, Integer timCalPeriod, Character timIsActive,
			String timItemPurchaseType, Character timIsSpareRequired,
			Character timIsSerialRequired, String timIsBuilding,
			String timShowScreen) {
		this.timId = timId;
		this.timItemName = timItemName;
		this.timItemCode = timItemCode;
		this.timCheckType = timCheckType;
		this.timCheckPeriod = timCheckPeriod;
		this.timTimeCost = timTimeCost;
		this.timTestsPerItem = timTestsPerItem;
		this.timRepairTime = timRepairTime;
		this.timServiceTime = timServiceTime;
		this.timPeriodicCal = timPeriodicCal;
		this.timCalPeriod = timCalPeriod;
		this.timIsActive = timIsActive;
		this.timItemPurchaseType = timItemPurchaseType;
		this.timIsSpareRequired = timIsSpareRequired;
		this.timIsSerialRequired = timIsSerialRequired;
		this.timIsBuilding = timIsBuilding;
		this.timShowScreen = timShowScreen;
	}

	@Id
	@Column(name = "tim_id", unique = true, nullable = false)
	public int getTimId() {
		return this.timId;
	}

	public void setTimId(int timId) {
		this.timId = timId;
	}

	@Column(name = "tim_item_name", length = 50)
	public String getTimItemName() {
		return this.timItemName;
	}

	public void setTimItemName(String timItemName) {
		this.timItemName = timItemName;
	}

	@Column(name = "tim_item_code", length = 10)
	public String getTimItemCode() {
		return this.timItemCode;
	}

	public void setTimItemCode(String timItemCode) {
		this.timItemCode = timItemCode;
	}

	@Column(name = "tim_check_type", length = 10)
	public String getTimCheckType() {
		return this.timCheckType;
	}

	public void setTimCheckType(String timCheckType) {
		this.timCheckType = timCheckType;
	}

	@Column(name = "tim_check_period")
	public Integer getTimCheckPeriod() {
		return this.timCheckPeriod;
	}

	public void setTimCheckPeriod(Integer timCheckPeriod) {
		this.timCheckPeriod = timCheckPeriod;
	}

	@Column(name = "tim_time_cost")
	public Integer getTimTimeCost() {
		return this.timTimeCost;
	}

	public void setTimTimeCost(Integer timTimeCost) {
		this.timTimeCost = timTimeCost;
	}

	@Column(name = "tim_tests_per_item")
	public Integer getTimTestsPerItem() {
		return this.timTestsPerItem;
	}

	public void setTimTestsPerItem(Integer timTestsPerItem) {
		this.timTestsPerItem = timTestsPerItem;
	}

	@Column(name = "tim_repair_time")
	public Integer getTimRepairTime() {
		return this.timRepairTime;
	}

	public void setTimRepairTime(Integer timRepairTime) {
		this.timRepairTime = timRepairTime;
	}

	@Column(name = "tim_service_time")
	public Integer getTimServiceTime() {
		return this.timServiceTime;
	}

	public void setTimServiceTime(Integer timServiceTime) {
		this.timServiceTime = timServiceTime;
	}

	@Column(name = "tim_periodic_cal", length = 1)
	public String getTimPeriodicCal() {
		return this.timPeriodicCal;
	}

	public void setTimPeriodicCal(String timPeriodicCal) {
		this.timPeriodicCal = timPeriodicCal;
	}

	@Column(name = "tim_cal_period")
	public Integer getTimCalPeriod() {
		return this.timCalPeriod;
	}

	public void setTimCalPeriod(Integer timCalPeriod) {
		this.timCalPeriod = timCalPeriod;
	}

	@Column(name = "tim_is_active", length = 1)
	public Character getTimIsActive() {
		return this.timIsActive;
	}

	public void setTimIsActive(Character timIsActive) {
		this.timIsActive = timIsActive;
	}

	@Column(name = "tim_item_purchase_type", length = 2)
	public String getTimItemPurchaseType() {
		return this.timItemPurchaseType;
	}

	public void setTimItemPurchaseType(String timItemPurchaseType) {
		this.timItemPurchaseType = timItemPurchaseType;
	}

	@Column(name = "tim_is_spare_required", length = 1)
	public Character getTimIsSpareRequired() {
		return this.timIsSpareRequired;
	}

	public void setTimIsSpareRequired(Character timIsSpareRequired) {
		this.timIsSpareRequired = timIsSpareRequired;
	}

	@Column(name = "tim_is_serial_required", length = 1)
	public Character getTimIsSerialRequired() {
		return this.timIsSerialRequired;
	}

	public void setTimIsSerialRequired(Character timIsSerialRequired) {
		this.timIsSerialRequired = timIsSerialRequired;
	}

	@Column(name = "tim_is_building", length = 1)
	public String getTimIsBuilding() {
		return this.timIsBuilding;
	}

	public void setTimIsBuilding(String timIsBuilding) {
		this.timIsBuilding = timIsBuilding;
	}

	@Column(name = "tim_show_screen", length = 40)
	public String getTimShowScreen() {
		return this.timShowScreen;
	}

	public void setTimShowScreen(String timShowScreen) {
		this.timShowScreen = timShowScreen;
	}

}
