package com.bt.nat.item;
// default package
// Generated 17-Feb-2014 13:57:10 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TEsitestFescCheckTypesId generated by hbm2java
 */
@Entity
@Table(name = "t_esitest_fesc_check_types")
public class TEsitestFescCheckTypes implements java.io.Serializable {

	private int fctId;
	private String fctCheckTypeDescription;
	private String fctCheckType;
	private String fctItemStatusColumn;
	private String fctEsitestType;

	public TEsitestFescCheckTypes() {
	}

	public TEsitestFescCheckTypes(int fctId) {
		this.fctId = fctId;
	}

	public TEsitestFescCheckTypes(int fctId, String fctCheckTypeDescription,
			String fctCheckType, String fctItemStatusColumn,
			String fctEsitestType) {
		this.fctId = fctId;
		this.fctCheckTypeDescription = fctCheckTypeDescription;
		this.fctCheckType = fctCheckType;
		this.fctItemStatusColumn = fctItemStatusColumn;
		this.fctEsitestType = fctEsitestType;
	}

	@Id
	@Column(name = "fct_id", nullable = false)
	public int getFctId() {
		return this.fctId;
	}

	public void setFctId(int fctId) {
		this.fctId = fctId;
	}

	@Column(name = "fct_check_type_description", length = 50)
	public String getFctCheckTypeDescription() {
		return this.fctCheckTypeDescription;
	}

	public void setFctCheckTypeDescription(String fctCheckTypeDescription) {
		this.fctCheckTypeDescription = fctCheckTypeDescription;
	}

	@Column(name = "fct_check_type", length = 1)
	public String getFctCheckType() {
		return this.fctCheckType;
	}

	public void setFctCheckType(String fctCheckType) {
		this.fctCheckType = fctCheckType;
	}

	@Column(name = "fct_item_status_column", length = 30)
	public String getFctItemStatusColumn() {
		return this.fctItemStatusColumn;
	}

	public void setFctItemStatusColumn(String fctItemStatusColumn) {
		this.fctItemStatusColumn = fctItemStatusColumn;
	}

	@Column(name = "fct_esitest_type", length = 20)
	public String getFctEsitestType() {
		return this.fctEsitestType;
	}

	public void setFctEsitestType(String fctEsitestType) {
		this.fctEsitestType = fctEsitestType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TEsitestFescCheckTypes))
			return false;
		TEsitestFescCheckTypes castOther = (TEsitestFescCheckTypes) other;

		return (this.getFctId() == castOther.getFctId())
				&& ((this.getFctCheckTypeDescription() == castOther
						.getFctCheckTypeDescription()) || (this
						.getFctCheckTypeDescription() != null
						&& castOther.getFctCheckTypeDescription() != null && this
						.getFctCheckTypeDescription().equals(
								castOther.getFctCheckTypeDescription())))
				&& ((this.getFctCheckType() == castOther.getFctCheckType()) || (this
						.getFctCheckType() != null
						&& castOther.getFctCheckType() != null && this
						.getFctCheckType().equals(castOther.getFctCheckType())))
				&& ((this.getFctItemStatusColumn() == castOther
						.getFctItemStatusColumn()) || (this
						.getFctItemStatusColumn() != null
						&& castOther.getFctItemStatusColumn() != null && this
						.getFctItemStatusColumn().equals(
								castOther.getFctItemStatusColumn())))
				&& ((this.getFctEsitestType() == castOther.getFctEsitestType()) || (this
						.getFctEsitestType() != null
						&& castOther.getFctEsitestType() != null && this
						.getFctEsitestType().equals(
								castOther.getFctEsitestType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFctId();
		result = 37
				* result
				+ (getFctCheckTypeDescription() == null ? 0 : this
						.getFctCheckTypeDescription().hashCode());
		result = 37
				* result
				+ (getFctCheckType() == null ? 0 : this.getFctCheckType()
						.hashCode());
		result = 37
				* result
				+ (getFctItemStatusColumn() == null ? 0 : this
						.getFctItemStatusColumn().hashCode());
		result = 37
				* result
				+ (getFctEsitestType() == null ? 0 : this.getFctEsitestType()
						.hashCode());
		return result;
	}

}
