package com.bt.nat.item;
// default package
// Generated 14-Feb-2014 15:30:39 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TEsitestItemTestingDetailsId generated by hbm2java
 */
@Embeddable
public class TEsitestItemTestingDetailsId implements java.io.Serializable {

	private long itdId;
	private Long itdTeiId;
	private String itdTestingStatus;
	private Date itdTestingDate;
	private Long itdEsiId;
	private Integer itdTestedByEin;

	public TEsitestItemTestingDetailsId() {
	}

	public TEsitestItemTestingDetailsId(long itdId) {
		this.itdId = itdId;
	}

	public TEsitestItemTestingDetailsId(long itdId, Long itdTeiId,
			String itdTestingStatus, Date itdTestingDate, Long itdEsiId,
			Integer itdTestedByEin) {
		this.itdId = itdId;
		this.itdTeiId = itdTeiId;
		this.itdTestingStatus = itdTestingStatus;
		this.itdTestingDate = itdTestingDate;
		this.itdEsiId = itdEsiId;
		this.itdTestedByEin = itdTestedByEin;
	}

	@Column(name = "itd_id", nullable = false)
	public long getItdId() {
		return this.itdId;
	}

	public void setItdId(long itdId) {
		this.itdId = itdId;
	}

	@Column(name = "itd_tei_id")
	public Long getItdTeiId() {
		return this.itdTeiId;
	}

	public void setItdTeiId(Long itdTeiId) {
		this.itdTeiId = itdTeiId;
	}

	@Column(name = "itd_testing_status", length = 1)
	public String getItdTestingStatus() {
		return this.itdTestingStatus;
	}

	public void setItdTestingStatus(String itdTestingStatus) {
		this.itdTestingStatus = itdTestingStatus;
	}

	@Column(name = "itd_testing_date", length = 23)
	public Date getItdTestingDate() {
		return this.itdTestingDate;
	}

	public void setItdTestingDate(Date itdTestingDate) {
		this.itdTestingDate = itdTestingDate;
	}

	@Column(name = "itd_esi_id")
	public Long getItdEsiId() {
		return this.itdEsiId;
	}

	public void setItdEsiId(Long itdEsiId) {
		this.itdEsiId = itdEsiId;
	}

	@Column(name = "itd_tested_by_ein")
	public Integer getItdTestedByEin() {
		return this.itdTestedByEin;
	}

	public void setItdTestedByEin(Integer itdTestedByEin) {
		this.itdTestedByEin = itdTestedByEin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TEsitestItemTestingDetailsId))
			return false;
		TEsitestItemTestingDetailsId castOther = (TEsitestItemTestingDetailsId) other;

		return (this.getItdId() == castOther.getItdId())
				&& ((this.getItdTeiId() == castOther.getItdTeiId()) || (this
						.getItdTeiId() != null
						&& castOther.getItdTeiId() != null && this
						.getItdTeiId().equals(castOther.getItdTeiId())))
				&& ((this.getItdTestingStatus() == castOther
						.getItdTestingStatus()) || (this.getItdTestingStatus() != null
						&& castOther.getItdTestingStatus() != null && this
						.getItdTestingStatus().equals(
								castOther.getItdTestingStatus())))
				&& ((this.getItdTestingDate() == castOther.getItdTestingDate()) || (this
						.getItdTestingDate() != null
						&& castOther.getItdTestingDate() != null && this
						.getItdTestingDate().equals(
								castOther.getItdTestingDate())))
				&& ((this.getItdEsiId() == castOther.getItdEsiId()) || (this
						.getItdEsiId() != null
						&& castOther.getItdEsiId() != null && this
						.getItdEsiId().equals(castOther.getItdEsiId())))
				&& ((this.getItdTestedByEin() == castOther.getItdTestedByEin()) || (this
						.getItdTestedByEin() != null
						&& castOther.getItdTestedByEin() != null && this
						.getItdTestedByEin().equals(
								castOther.getItdTestedByEin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getItdId();
		result = 37 * result
				+ (getItdTeiId() == null ? 0 : this.getItdTeiId().hashCode());
		result = 37
				* result
				+ (getItdTestingStatus() == null ? 0 : this
						.getItdTestingStatus().hashCode());
		result = 37
				* result
				+ (getItdTestingDate() == null ? 0 : this.getItdTestingDate()
						.hashCode());
		result = 37 * result
				+ (getItdEsiId() == null ? 0 : this.getItdEsiId().hashCode());
		result = 37
				* result
				+ (getItdTestedByEin() == null ? 0 : this.getItdTestedByEin()
						.hashCode());
		return result;
	}

}
