package com.bt.nat.home;

// default package
// Generated 18-Feb-2014 11:13:07 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * TEsitestMainMenuButtonsId generated by hbm2java
 */
@Entity
@Table(name = "t_esitest_main_menu_buttons")
@NamedQueries({
		@NamedQuery(name = TEsitestMainMenuButtons.FIND_BUTTONS, query = "select a from TEsitestMainMenuButtons a where a.mmbMmPrimaryButtonName = :name and a.mmbMmUserType in :type"),
		@NamedQuery(name = TEsitestMainMenuButtons.FIND_SUB_BUTTONS, query = "select a from TEsitestMainMenuButtons a where a.mmbMmPrimaryButtonName = :name") })
public class TEsitestMainMenuButtons implements java.io.Serializable {
	public static final String FIND_BUTTONS = "TEsitestMainMenuButtons.findButtons";
	public static final String FIND_SUB_BUTTONS = "TEsitestMainMenuButtons.findSubButtons";

	private int mmbId;
	private Integer mmbMmScreenOrder;
	private String mmbMmButtonName;
	private String mmbMmButtonDescription;
	private String mmbMmButtonUrl;
	private String mmbMmButtonTask;
	private String mmbMmUserType;
	private String mmbMmPrimaryButtonName;

	public TEsitestMainMenuButtons() {
	}

	public TEsitestMainMenuButtons(int mmbId) {
		this.mmbId = mmbId;
	}

	public TEsitestMainMenuButtons(int mmbId, Integer mmbMmScreenOrder,
			String mmbMmButtonName, String mmbMmButtonDescription,
			String mmbMmButtonUrl, String mmbMmButtonTask,
			String mmbMmUserType, String mmbMmPrimaryButtonName) {
		this.mmbId = mmbId;
		this.mmbMmScreenOrder = mmbMmScreenOrder;
		this.mmbMmButtonName = mmbMmButtonName;
		this.mmbMmButtonDescription = mmbMmButtonDescription;
		this.mmbMmButtonUrl = mmbMmButtonUrl;
		this.mmbMmButtonTask = mmbMmButtonTask;
		this.mmbMmUserType = mmbMmUserType;
		this.mmbMmPrimaryButtonName = mmbMmPrimaryButtonName;
	}

	@Id
	@Column(name = "mmb_id", nullable = false)
	public int getMmbId() {
		return this.mmbId;
	}

	public void setMmbId(int mmbId) {
		this.mmbId = mmbId;
	}

	@Column(name = "mmb_mm_screen_order")
	public Integer getMmbMmScreenOrder() {
		return this.mmbMmScreenOrder;
	}

	public void setMmbMmScreenOrder(Integer mmbMmScreenOrder) {
		this.mmbMmScreenOrder = mmbMmScreenOrder;
	}

	@Column(name = "mmb_mm_button_name", length = 30)
	public String getMmbMmButtonName() {
		return this.mmbMmButtonName;
	}

	public void setMmbMmButtonName(String mmbMmButtonName) {
		this.mmbMmButtonName = mmbMmButtonName;
	}

	@Column(name = "mmb_mm_button_description", length = 100)
	public String getMmbMmButtonDescription() {
		return this.mmbMmButtonDescription;
	}

	public void setMmbMmButtonDescription(String mmbMmButtonDescription) {
		this.mmbMmButtonDescription = mmbMmButtonDescription;
	}

	@Column(name = "mmb_mm_button_url", length = 100)
	public String getMmbMmButtonUrl() {
		return this.mmbMmButtonUrl;
	}

	public void setMmbMmButtonUrl(String mmbMmButtonUrl) {
		this.mmbMmButtonUrl = mmbMmButtonUrl;
	}

	@Column(name = "mmb_mm_button_task", length = 100)
	public String getMmbMmButtonTask() {
		return this.mmbMmButtonTask;
	}

	public void setMmbMmButtonTask(String mmbMmButtonTask) {
		this.mmbMmButtonTask = mmbMmButtonTask;
	}

	@Column(name = "mmb_mm_user_type", length = 50)
	public String getMmbMmUserType() {
		return this.mmbMmUserType;
	}

	public void setMmbMmUserType(String mmbMmUserType) {
		this.mmbMmUserType = mmbMmUserType;
	}

	@Column(name = "mmb_mm_primary_button_name", length = 50)
	public String getMmbMmPrimaryButtonName() {
		return this.mmbMmPrimaryButtonName;
	}

	public void setMmbMmPrimaryButtonName(String mmbMmPrimaryButtonName) {
		this.mmbMmPrimaryButtonName = mmbMmPrimaryButtonName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TEsitestMainMenuButtons))
			return false;
		TEsitestMainMenuButtons castOther = (TEsitestMainMenuButtons) other;

		return (this.getMmbId() == castOther.getMmbId())
				&& ((this.getMmbMmScreenOrder() == castOther
						.getMmbMmScreenOrder()) || (this.getMmbMmScreenOrder() != null
						&& castOther.getMmbMmScreenOrder() != null && this
						.getMmbMmScreenOrder().equals(
								castOther.getMmbMmScreenOrder())))
				&& ((this.getMmbMmButtonName() == castOther
						.getMmbMmButtonName()) || (this.getMmbMmButtonName() != null
						&& castOther.getMmbMmButtonName() != null && this
						.getMmbMmButtonName().equals(
								castOther.getMmbMmButtonName())))
				&& ((this.getMmbMmButtonDescription() == castOther
						.getMmbMmButtonDescription()) || (this
						.getMmbMmButtonDescription() != null
						&& castOther.getMmbMmButtonDescription() != null && this
						.getMmbMmButtonDescription().equals(
								castOther.getMmbMmButtonDescription())))
				&& ((this.getMmbMmButtonUrl() == castOther.getMmbMmButtonUrl()) || (this
						.getMmbMmButtonUrl() != null
						&& castOther.getMmbMmButtonUrl() != null && this
						.getMmbMmButtonUrl().equals(
								castOther.getMmbMmButtonUrl())))
				&& ((this.getMmbMmButtonTask() == castOther
						.getMmbMmButtonTask()) || (this.getMmbMmButtonTask() != null
						&& castOther.getMmbMmButtonTask() != null && this
						.getMmbMmButtonTask().equals(
								castOther.getMmbMmButtonTask())))
				&& ((this.getMmbMmUserType() == castOther.getMmbMmUserType()) || (this
						.getMmbMmUserType() != null
						&& castOther.getMmbMmUserType() != null && this
						.getMmbMmUserType()
						.equals(castOther.getMmbMmUserType())))
				&& ((this.getMmbMmPrimaryButtonName() == castOther
						.getMmbMmPrimaryButtonName()) || (this
						.getMmbMmPrimaryButtonName() != null
						&& castOther.getMmbMmPrimaryButtonName() != null && this
						.getMmbMmPrimaryButtonName().equals(
								castOther.getMmbMmPrimaryButtonName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMmbId();
		result = 37
				* result
				+ (getMmbMmScreenOrder() == null ? 0 : this
						.getMmbMmScreenOrder().hashCode());
		result = 37
				* result
				+ (getMmbMmButtonName() == null ? 0 : this.getMmbMmButtonName()
						.hashCode());
		result = 37
				* result
				+ (getMmbMmButtonDescription() == null ? 0 : this
						.getMmbMmButtonDescription().hashCode());
		result = 37
				* result
				+ (getMmbMmButtonUrl() == null ? 0 : this.getMmbMmButtonUrl()
						.hashCode());
		result = 37
				* result
				+ (getMmbMmButtonTask() == null ? 0 : this.getMmbMmButtonTask()
						.hashCode());
		result = 37
				* result
				+ (getMmbMmUserType() == null ? 0 : this.getMmbMmUserType()
						.hashCode());
		result = 37
				* result
				+ (getMmbMmPrimaryButtonName() == null ? 0 : this
						.getMmbMmPrimaryButtonName().hashCode());
		return result;
	}

}
