package com.bt.nat.building;

// default package
// Generated 18-Feb-2014 11:13:07 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import com.bt.nat.item.TEsitestItemMaster;

/**
 * TEsitestBuildingsId generated by hbm2java
 */
@Entity
@Table(name = "t_esitest_buildings")
@NamedQuery(name = TEsitestBuildings.FIND_ALL, query = "select a from TEsitestBuildings a")
public class TEsitestBuildings implements java.io.Serializable {

	public static final String FIND_ALL = "TEsitestBuildings.findAll";

	private int tebId;
	private String tebSkycode;
	private String tebBuildingName;
	private String tebTown;
	private String tebPostCode;
	private Integer tebTesterEin;
	private String tebIsActive;

	public TEsitestBuildings() {
	}

	public TEsitestBuildings(int tebId) {
		this.tebId = tebId;
	}

	public TEsitestBuildings(int tebId, String tebSkycode,
			String tebBuildingName, String tebTown, String tebPostCode,
			Integer tebTesterEin, String tebIsActive) {
		this.tebId = tebId;
		this.tebSkycode = tebSkycode;
		this.tebBuildingName = tebBuildingName;
		this.tebTown = tebTown;
		this.tebPostCode = tebPostCode;
		this.tebTesterEin = tebTesterEin;
		this.tebIsActive = tebIsActive;
	}

	@Id
	@Column(name = "teb_id", nullable = false)
	public int getTebId() {
		return this.tebId;
	}

	public void setTebId(int tebId) {
		this.tebId = tebId;
	}

	@Column(name = "teb_SKYCODE", length = 20)
	public String getTebSkycode() {
		return this.tebSkycode;
	}

	public void setTebSkycode(String tebSkycode) {
		this.tebSkycode = tebSkycode;
	}

	@Column(name = "teb_BUILDING_NAME", length = 50)
	public String getTebBuildingName() {
		return this.tebBuildingName;
	}

	public void setTebBuildingName(String tebBuildingName) {
		this.tebBuildingName = tebBuildingName;
	}

	@Column(name = "teb_TOWN", length = 50)
	public String getTebTown() {
		return this.tebTown;
	}

	public void setTebTown(String tebTown) {
		this.tebTown = tebTown;
	}

	@Column(name = "teb_POST_CODE", length = 10)
	public String getTebPostCode() {
		return this.tebPostCode;
	}

	public void setTebPostCode(String tebPostCode) {
		this.tebPostCode = tebPostCode;
	}

	@Column(name = "teb_tester_ein")
	public Integer getTebTesterEin() {
		return this.tebTesterEin;
	}

	public void setTebTesterEin(Integer tebTesterEin) {
		this.tebTesterEin = tebTesterEin;
	}

	@Column(name = "teb_is_active", length = 1)
	public String getTebIsActive() {
		return this.tebIsActive;
	}

	public void setTebIsActive(String tebIsActive) {
		this.tebIsActive = tebIsActive;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TEsitestBuildings))
			return false;
		TEsitestBuildings castOther = (TEsitestBuildings) other;

		return (this.getTebId() == castOther.getTebId())
				&& ((this.getTebSkycode() == castOther.getTebSkycode()) || (this
						.getTebSkycode() != null
						&& castOther.getTebSkycode() != null && this
						.getTebSkycode().equals(castOther.getTebSkycode())))
				&& ((this.getTebBuildingName() == castOther
						.getTebBuildingName()) || (this.getTebBuildingName() != null
						&& castOther.getTebBuildingName() != null && this
						.getTebBuildingName().equals(
								castOther.getTebBuildingName())))
				&& ((this.getTebTown() == castOther.getTebTown()) || (this
						.getTebTown() != null && castOther.getTebTown() != null && this
						.getTebTown().equals(castOther.getTebTown())))
				&& ((this.getTebPostCode() == castOther.getTebPostCode()) || (this
						.getTebPostCode() != null
						&& castOther.getTebPostCode() != null && this
						.getTebPostCode().equals(castOther.getTebPostCode())))
				&& ((this.getTebTesterEin() == castOther.getTebTesterEin()) || (this
						.getTebTesterEin() != null
						&& castOther.getTebTesterEin() != null && this
						.getTebTesterEin().equals(castOther.getTebTesterEin())))
				&& ((this.getTebIsActive() == castOther.getTebIsActive()) || (this
						.getTebIsActive() != null
						&& castOther.getTebIsActive() != null && this
						.getTebIsActive().equals(castOther.getTebIsActive())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTebId();
		result = 37
				* result
				+ (getTebSkycode() == null ? 0 : this.getTebSkycode()
						.hashCode());
		result = 37
				* result
				+ (getTebBuildingName() == null ? 0 : this.getTebBuildingName()
						.hashCode());
		result = 37 * result
				+ (getTebTown() == null ? 0 : this.getTebTown().hashCode());
		result = 37
				* result
				+ (getTebPostCode() == null ? 0 : this.getTebPostCode()
						.hashCode());
		result = 37
				* result
				+ (getTebTesterEin() == null ? 0 : this.getTebTesterEin()
						.hashCode());
		result = 37
				* result
				+ (getTebIsActive() == null ? 0 : this.getTebIsActive()
						.hashCode());
		return result;
	}

}
