package com.bt.nat.esitest;

// default package
// Generated 21-Feb-2014 16:14:57 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.bt.nat.building.TEsitestBuildings;
import com.bt.nat.engineer.TEsitestEngineerPostcode;
import com.bt.nat.item.TEsitestFescCheckTypes;

/**
 * TEsitestRecordsId generated by hbm2java
 */
@Entity
@Table(name = "t_esitest_records")
@NamedQueries({
		@NamedQuery(name = TEsitestRecords.FIND_BY_EIN_DUE, query = "select a.esiId,"
				+ "f.epoTesterEin,"
				+ "a.esiDueDate,"
				+ " e.tebBuildingName,"
				+ "c.fctCheckTypeDescription"
				+ " from TEsitestRecords as a "
				+ " left join a.engineerPostcode as b"
				+ " left join b.teePostcode as f"
				+ " left join a.checkTypes as c"
				+ " left join a.details as d"
				+ " left join a.buildings as e"
				+ " where a.esiEngineerEin = :ein and a.esiStatus !='MSO' and a.esiDueDate >= CURRENT_TIMESTAMP"),

		@NamedQuery(name = TEsitestRecords.FIND_BY_EIN_OVERDUE, query = "select a.esiId,"
				+ "f.epoTesterEin,"
				+ "a.esiDueDate,a.esiStatus,"
				+ " e.tebBuildingName,"
				+ "c.fctCheckTypeDescription,"
				+ "d.eedEscalatedLevel,"
				+ "(case when d.eedEscalatedLevel = 0 then 'No' WHEN "
				+ "d.eedEscalatedLevel is NULL then 'No' else 'Yes' END) as Escalated,"
				+ "(case when d.eedEscalatedLevel = 0 then 0 "
				+ " when d.eedEscalatedLevel is NULL then 0 "
				+ " when d.eedEscalatedLevel = 1 then d.eedEscalatedLevel1Ein "
				+ " when d.eedEscalatedLevel = 2 then d.eedEscalatedLevel2Ein"
				+ " when d.eedEscalatedLevel = 3 then d.eedEscalatedLevel3Ein END) as manager"
				+ " from TEsitestRecords as a "
				+ " left join a.engineerPostcode as b"
				+ " left join b.teePostcode as f"
				+ " left join a.checkTypes as c"
				+ " left join a.escalationDetails as d"
				+ " left join a.buildings as e"
				+ " where a.esiEngineerEin = :ein and a.esiStatus !='MSO' and a.esiDueDate < CURRENT_TIMESTAMP") })
public class TEsitestRecords implements java.io.Serializable {

	public static final String FIND_BY_EIN_DUE = "TEsitestRecords.findByEinDue";
	public static final String FIND_BY_EIN_OVERDUE = "TEsitestRecords.findByEinOverDue";

	private long esiId;
	private Integer esiEngineerEin;
	private Date esiDueDate;
	private String esiStatus;
	private String esiIsBuilding;

	private TEsitestEscalationDetails details;

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "esi_id", referencedColumnName = "eed_esi_id", insertable = false, updatable = false)
	public TEsitestEscalationDetails getDetails() {
		return details;
	}

	public void setDetails(TEsitestEscalationDetails details) {
		this.details = details;
	}

	private TEsitestBuildings buildings;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "esi_teb_id", referencedColumnName = "teb_id")
	public TEsitestBuildings getBuildings() {
		return buildings;
	}

	public void setBuildings(TEsitestBuildings buildings) {
		this.buildings = buildings;
	}

	private TEsitestFescCheckTypes checkTypes;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "esi_type", referencedColumnName = "fct_check_type")
	public TEsitestFescCheckTypes getCheckTypes() {
		return checkTypes;
	}

	public void setCheckTypes(TEsitestFescCheckTypes checkTypes) {
		this.checkTypes = checkTypes;
	}

	private TEsitestEngineerPostcode engineerPostcode;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "esi_engineer_ein", referencedColumnName = "tee_engineer_ein", insertable = false, updatable = false)
	public TEsitestEngineerPostcode getEngineerPostcode() {
		return engineerPostcode;
	}

	public void setEngineerPostcode(TEsitestEngineerPostcode engineerPostcode) {
		this.engineerPostcode = engineerPostcode;
	}

	private TEsitestEscalationDetails escalationDetails;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "esi_id", referencedColumnName = "eed_esi_id",insertable=false,updatable=false)
	public TEsitestEscalationDetails getEscalationDetails() {
		return escalationDetails;
	}

	public void setEscalationDetails(TEsitestEscalationDetails escalationDetails) {
		this.escalationDetails = escalationDetails;
	}
	
	
	private Integer esiMsoEin;
	

	private Integer esiAppeLookahead;
	private Integer esiGasLookahead;
	private Integer esiEliftLookahead;
	private Integer esiElecLookahead;
	private Integer esiClimbLookahead;
	private Integer esiMechLookahead;
	private Integer esiOtmLookahead;
	private Integer esiPpeLookahead;
	private Integer esiPullLookahead;
	private Integer esiAppeItemCount;
	private Integer esiGasItemCount;
	private Integer esiEliftItemCount;
	private Integer esiElecItemCount;
	private Integer esiClimbItemCount;
	private Integer esiMechItemCount;
	private Integer esiOtmItemCount;
	private Integer esiPpeItemCount;
	private Integer esiPullItemCount;
	private Boolean esiMsoEmailSent;
	private Date esiCompletedDate;

	public TEsitestRecords() {
	}

	public TEsitestRecords(long esiId) {
		this.esiId = esiId;
	}

	public TEsitestRecords(long esiId, Integer esiEngineerEin, Date esiDueDate,
			String esiStatus, String esiIsBuilding, Integer esiMsoEin,
			Integer esiAppeLookahead, Integer esiGasLookahead,
			Integer esiEliftLookahead, Integer esiElecLookahead,
			Integer esiClimbLookahead, Integer esiMechLookahead,
			Integer esiOtmLookahead, Integer esiPpeLookahead,
			Integer esiPullLookahead, Integer esiAppeItemCount,
			Integer esiGasItemCount, Integer esiEliftItemCount,
			Integer esiElecItemCount, Integer esiClimbItemCount,
			Integer esiMechItemCount, Integer esiOtmItemCount,
			Integer esiPpeItemCount, Integer esiPullItemCount,
			Boolean esiMsoEmailSent, Date esiCompletedDate) {
		this.esiId = esiId;
		this.esiEngineerEin = esiEngineerEin;
		this.esiDueDate = esiDueDate;
		this.esiStatus = esiStatus;
		this.esiIsBuilding = esiIsBuilding;
		this.esiMsoEin = esiMsoEin;
		this.esiAppeLookahead = esiAppeLookahead;
		this.esiGasLookahead = esiGasLookahead;
		this.esiEliftLookahead = esiEliftLookahead;
		this.esiElecLookahead = esiElecLookahead;
		this.esiClimbLookahead = esiClimbLookahead;
		this.esiMechLookahead = esiMechLookahead;
		this.esiOtmLookahead = esiOtmLookahead;
		this.esiPpeLookahead = esiPpeLookahead;
		this.esiPullLookahead = esiPullLookahead;
		this.esiAppeItemCount = esiAppeItemCount;
		this.esiGasItemCount = esiGasItemCount;
		this.esiEliftItemCount = esiEliftItemCount;
		this.esiElecItemCount = esiElecItemCount;
		this.esiClimbItemCount = esiClimbItemCount;
		this.esiMechItemCount = esiMechItemCount;
		this.esiOtmItemCount = esiOtmItemCount;
		this.esiPpeItemCount = esiPpeItemCount;
		this.esiPullItemCount = esiPullItemCount;
		this.esiMsoEmailSent = esiMsoEmailSent;
		this.esiCompletedDate = esiCompletedDate;
	}

	@Id
	@Column(name = "esi_id", nullable = false)
	public long getEsiId() {
		return this.esiId;
	}

	public void setEsiId(long esiId) {
		this.esiId = esiId;
	}

	@Column(name = "esi_engineer_ein")
	public Integer getEsiEngineerEin() {
		return this.esiEngineerEin;
	}

	public void setEsiEngineerEin(Integer esiEngineerEin) {
		this.esiEngineerEin = esiEngineerEin;
	}

	@Column(name = "esi_due_date", length = 23)
	public Date getEsiDueDate() {
		return this.esiDueDate;
	}

	public void setEsiDueDate(Date esiDueDate) {
		this.esiDueDate = esiDueDate;
	}

	@Column(name = "esi_status", length = 50)
	public String getEsiStatus() {
		return this.esiStatus;
	}

	public void setEsiStatus(String esiStatus) {
		this.esiStatus = esiStatus;
	}

	@Column(name = "esi_is_building", length = 1)
	public String getEsiIsBuilding() {
		return this.esiIsBuilding;
	}

	public void setEsiIsBuilding(String esiIsBuilding) {
		this.esiIsBuilding = esiIsBuilding;
	}

	@Column(name = "esi_mso_ein")
	public Integer getEsiMsoEin() {
		return this.esiMsoEin;
	}

	public void setEsiMsoEin(Integer esiMsoEin) {
		this.esiMsoEin = esiMsoEin;
	}

	@Column(name = "esi_appe_lookahead")
	public Integer getEsiAppeLookahead() {
		return this.esiAppeLookahead;
	}

	public void setEsiAppeLookahead(Integer esiAppeLookahead) {
		this.esiAppeLookahead = esiAppeLookahead;
	}

	@Column(name = "esi_gas_lookahead")
	public Integer getEsiGasLookahead() {
		return this.esiGasLookahead;
	}

	public void setEsiGasLookahead(Integer esiGasLookahead) {
		this.esiGasLookahead = esiGasLookahead;
	}

	@Column(name = "esi_elift_lookahead")
	public Integer getEsiEliftLookahead() {
		return this.esiEliftLookahead;
	}

	public void setEsiEliftLookahead(Integer esiEliftLookahead) {
		this.esiEliftLookahead = esiEliftLookahead;
	}

	@Column(name = "esi_elec_lookahead")
	public Integer getEsiElecLookahead() {
		return this.esiElecLookahead;
	}

	public void setEsiElecLookahead(Integer esiElecLookahead) {
		this.esiElecLookahead = esiElecLookahead;
	}

	@Column(name = "esi_climb_lookahead")
	public Integer getEsiClimbLookahead() {
		return this.esiClimbLookahead;
	}

	public void setEsiClimbLookahead(Integer esiClimbLookahead) {
		this.esiClimbLookahead = esiClimbLookahead;
	}

	@Column(name = "esi_mech_lookahead")
	public Integer getEsiMechLookahead() {
		return this.esiMechLookahead;
	}

	public void setEsiMechLookahead(Integer esiMechLookahead) {
		this.esiMechLookahead = esiMechLookahead;
	}

	@Column(name = "esi_otm_lookahead")
	public Integer getEsiOtmLookahead() {
		return this.esiOtmLookahead;
	}

	public void setEsiOtmLookahead(Integer esiOtmLookahead) {
		this.esiOtmLookahead = esiOtmLookahead;
	}

	@Column(name = "esi_ppe_lookahead")
	public Integer getEsiPpeLookahead() {
		return this.esiPpeLookahead;
	}

	public void setEsiPpeLookahead(Integer esiPpeLookahead) {
		this.esiPpeLookahead = esiPpeLookahead;
	}

	@Column(name = "esi_pull_lookahead")
	public Integer getEsiPullLookahead() {
		return this.esiPullLookahead;
	}

	public void setEsiPullLookahead(Integer esiPullLookahead) {
		this.esiPullLookahead = esiPullLookahead;
	}

	@Column(name = "esi_appe_item_count")
	public Integer getEsiAppeItemCount() {
		return this.esiAppeItemCount;
	}

	public void setEsiAppeItemCount(Integer esiAppeItemCount) {
		this.esiAppeItemCount = esiAppeItemCount;
	}

	@Column(name = "esi_gas_item_count")
	public Integer getEsiGasItemCount() {
		return this.esiGasItemCount;
	}

	public void setEsiGasItemCount(Integer esiGasItemCount) {
		this.esiGasItemCount = esiGasItemCount;
	}

	@Column(name = "esi_elift_item_count")
	public Integer getEsiEliftItemCount() {
		return this.esiEliftItemCount;
	}

	public void setEsiEliftItemCount(Integer esiEliftItemCount) {
		this.esiEliftItemCount = esiEliftItemCount;
	}

	@Column(name = "esi_elec_item_count")
	public Integer getEsiElecItemCount() {
		return this.esiElecItemCount;
	}

	public void setEsiElecItemCount(Integer esiElecItemCount) {
		this.esiElecItemCount = esiElecItemCount;
	}

	@Column(name = "esi_climb_item_count")
	public Integer getEsiClimbItemCount() {
		return this.esiClimbItemCount;
	}

	public void setEsiClimbItemCount(Integer esiClimbItemCount) {
		this.esiClimbItemCount = esiClimbItemCount;
	}

	@Column(name = "esi_mech_item_count")
	public Integer getEsiMechItemCount() {
		return this.esiMechItemCount;
	}

	public void setEsiMechItemCount(Integer esiMechItemCount) {
		this.esiMechItemCount = esiMechItemCount;
	}

	@Column(name = "esi_otm_item_count")
	public Integer getEsiOtmItemCount() {
		return this.esiOtmItemCount;
	}

	public void setEsiOtmItemCount(Integer esiOtmItemCount) {
		this.esiOtmItemCount = esiOtmItemCount;
	}

	@Column(name = "esi_ppe_item_count")
	public Integer getEsiPpeItemCount() {
		return this.esiPpeItemCount;
	}

	public void setEsiPpeItemCount(Integer esiPpeItemCount) {
		this.esiPpeItemCount = esiPpeItemCount;
	}

	@Column(name = "esi_pull_item_count")
	public Integer getEsiPullItemCount() {
		return this.esiPullItemCount;
	}

	public void setEsiPullItemCount(Integer esiPullItemCount) {
		this.esiPullItemCount = esiPullItemCount;
	}

	@Column(name = "esi_mso_email_sent")
	public Boolean getEsiMsoEmailSent() {
		return this.esiMsoEmailSent;
	}

	public void setEsiMsoEmailSent(Boolean esiMsoEmailSent) {
		this.esiMsoEmailSent = esiMsoEmailSent;
	}

	@Column(name = "esi_completed_date", length = 23)
	public Date getEsiCompletedDate() {
		return this.esiCompletedDate;
	}

	public void setEsiCompletedDate(Date esiCompletedDate) {
		this.esiCompletedDate = esiCompletedDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TEsitestRecords))
			return false;
		TEsitestRecords castOther = (TEsitestRecords) other;

		return (this.getEsiId() == castOther.getEsiId())
				&& ((this.getEsiEngineerEin() == castOther.getEsiEngineerEin()) || (this
						.getEsiEngineerEin() != null
						&& castOther.getEsiEngineerEin() != null && this
						.getEsiEngineerEin().equals(
								castOther.getEsiEngineerEin())))
				&& ((this.getEsiDueDate() == castOther.getEsiDueDate()) || (this
						.getEsiDueDate() != null
						&& castOther.getEsiDueDate() != null && this
						.getEsiDueDate().equals(castOther.getEsiDueDate())))
				&& ((this.getEsiStatus() == castOther.getEsiStatus()) || (this
						.getEsiStatus() != null
						&& castOther.getEsiStatus() != null && this
						.getEsiStatus().equals(castOther.getEsiStatus())))
				&& ((this.getEsiIsBuilding() == castOther.getEsiIsBuilding()) || (this
						.getEsiIsBuilding() != null
						&& castOther.getEsiIsBuilding() != null && this
						.getEsiIsBuilding()
						.equals(castOther.getEsiIsBuilding())))
				&& ((this.getEsiMsoEin() == castOther.getEsiMsoEin()) || (this
						.getEsiMsoEin() != null
						&& castOther.getEsiMsoEin() != null && this
						.getEsiMsoEin().equals(castOther.getEsiMsoEin())))
				&& ((this.getEsiAppeLookahead() == castOther
						.getEsiAppeLookahead()) || (this.getEsiAppeLookahead() != null
						&& castOther.getEsiAppeLookahead() != null && this
						.getEsiAppeLookahead().equals(
								castOther.getEsiAppeLookahead())))
				&& ((this.getEsiGasLookahead() == castOther
						.getEsiGasLookahead()) || (this.getEsiGasLookahead() != null
						&& castOther.getEsiGasLookahead() != null && this
						.getEsiGasLookahead().equals(
								castOther.getEsiGasLookahead())))
				&& ((this.getEsiEliftLookahead() == castOther
						.getEsiEliftLookahead()) || (this
						.getEsiEliftLookahead() != null
						&& castOther.getEsiEliftLookahead() != null && this
						.getEsiEliftLookahead().equals(
								castOther.getEsiEliftLookahead())))
				&& ((this.getEsiElecLookahead() == castOther
						.getEsiElecLookahead()) || (this.getEsiElecLookahead() != null
						&& castOther.getEsiElecLookahead() != null && this
						.getEsiElecLookahead().equals(
								castOther.getEsiElecLookahead())))
				&& ((this.getEsiClimbLookahead() == castOther
						.getEsiClimbLookahead()) || (this
						.getEsiClimbLookahead() != null
						&& castOther.getEsiClimbLookahead() != null && this
						.getEsiClimbLookahead().equals(
								castOther.getEsiClimbLookahead())))
				&& ((this.getEsiMechLookahead() == castOther
						.getEsiMechLookahead()) || (this.getEsiMechLookahead() != null
						&& castOther.getEsiMechLookahead() != null && this
						.getEsiMechLookahead().equals(
								castOther.getEsiMechLookahead())))
				&& ((this.getEsiOtmLookahead() == castOther
						.getEsiOtmLookahead()) || (this.getEsiOtmLookahead() != null
						&& castOther.getEsiOtmLookahead() != null && this
						.getEsiOtmLookahead().equals(
								castOther.getEsiOtmLookahead())))
				&& ((this.getEsiPpeLookahead() == castOther
						.getEsiPpeLookahead()) || (this.getEsiPpeLookahead() != null
						&& castOther.getEsiPpeLookahead() != null && this
						.getEsiPpeLookahead().equals(
								castOther.getEsiPpeLookahead())))
				&& ((this.getEsiPullLookahead() == castOther
						.getEsiPullLookahead()) || (this.getEsiPullLookahead() != null
						&& castOther.getEsiPullLookahead() != null && this
						.getEsiPullLookahead().equals(
								castOther.getEsiPullLookahead())))
				&& ((this.getEsiAppeItemCount() == castOther
						.getEsiAppeItemCount()) || (this.getEsiAppeItemCount() != null
						&& castOther.getEsiAppeItemCount() != null && this
						.getEsiAppeItemCount().equals(
								castOther.getEsiAppeItemCount())))
				&& ((this.getEsiGasItemCount() == castOther
						.getEsiGasItemCount()) || (this.getEsiGasItemCount() != null
						&& castOther.getEsiGasItemCount() != null && this
						.getEsiGasItemCount().equals(
								castOther.getEsiGasItemCount())))
				&& ((this.getEsiEliftItemCount() == castOther
						.getEsiEliftItemCount()) || (this
						.getEsiEliftItemCount() != null
						&& castOther.getEsiEliftItemCount() != null && this
						.getEsiEliftItemCount().equals(
								castOther.getEsiEliftItemCount())))
				&& ((this.getEsiElecItemCount() == castOther
						.getEsiElecItemCount()) || (this.getEsiElecItemCount() != null
						&& castOther.getEsiElecItemCount() != null && this
						.getEsiElecItemCount().equals(
								castOther.getEsiElecItemCount())))
				&& ((this.getEsiClimbItemCount() == castOther
						.getEsiClimbItemCount()) || (this
						.getEsiClimbItemCount() != null
						&& castOther.getEsiClimbItemCount() != null && this
						.getEsiClimbItemCount().equals(
								castOther.getEsiClimbItemCount())))
				&& ((this.getEsiMechItemCount() == castOther
						.getEsiMechItemCount()) || (this.getEsiMechItemCount() != null
						&& castOther.getEsiMechItemCount() != null && this
						.getEsiMechItemCount().equals(
								castOther.getEsiMechItemCount())))
				&& ((this.getEsiOtmItemCount() == castOther
						.getEsiOtmItemCount()) || (this.getEsiOtmItemCount() != null
						&& castOther.getEsiOtmItemCount() != null && this
						.getEsiOtmItemCount().equals(
								castOther.getEsiOtmItemCount())))
				&& ((this.getEsiPpeItemCount() == castOther
						.getEsiPpeItemCount()) || (this.getEsiPpeItemCount() != null
						&& castOther.getEsiPpeItemCount() != null && this
						.getEsiPpeItemCount().equals(
								castOther.getEsiPpeItemCount())))
				&& ((this.getEsiPullItemCount() == castOther
						.getEsiPullItemCount()) || (this.getEsiPullItemCount() != null
						&& castOther.getEsiPullItemCount() != null && this
						.getEsiPullItemCount().equals(
								castOther.getEsiPullItemCount())))
				&& ((this.getEsiMsoEmailSent() == castOther
						.getEsiMsoEmailSent()) || (this.getEsiMsoEmailSent() != null
						&& castOther.getEsiMsoEmailSent() != null && this
						.getEsiMsoEmailSent().equals(
								castOther.getEsiMsoEmailSent())))
				&& ((this.getEsiCompletedDate() == castOther
						.getEsiCompletedDate()) || (this.getEsiCompletedDate() != null
						&& castOther.getEsiCompletedDate() != null && this
						.getEsiCompletedDate().equals(
								castOther.getEsiCompletedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getEsiId();
		result = 37
				* result
				+ (getEsiEngineerEin() == null ? 0 : this.getEsiEngineerEin()
						.hashCode());
		result = 37
				* result
				+ (getEsiDueDate() == null ? 0 : this.getEsiDueDate()
						.hashCode());
		result = 37 * result
				+ (getEsiStatus() == null ? 0 : this.getEsiStatus().hashCode());
		result = 37
				* result
				+ (getEsiIsBuilding() == null ? 0 : this.getEsiIsBuilding()
						.hashCode());
		result = 37 * result
				+ (getEsiMsoEin() == null ? 0 : this.getEsiMsoEin().hashCode());
		result = 37
				* result
				+ (getEsiAppeLookahead() == null ? 0 : this
						.getEsiAppeLookahead().hashCode());
		result = 37
				* result
				+ (getEsiGasLookahead() == null ? 0 : this.getEsiGasLookahead()
						.hashCode());
		result = 37
				* result
				+ (getEsiEliftLookahead() == null ? 0 : this
						.getEsiEliftLookahead().hashCode());
		result = 37
				* result
				+ (getEsiElecLookahead() == null ? 0 : this
						.getEsiElecLookahead().hashCode());
		result = 37
				* result
				+ (getEsiClimbLookahead() == null ? 0 : this
						.getEsiClimbLookahead().hashCode());
		result = 37
				* result
				+ (getEsiMechLookahead() == null ? 0 : this
						.getEsiMechLookahead().hashCode());
		result = 37
				* result
				+ (getEsiOtmLookahead() == null ? 0 : this.getEsiOtmLookahead()
						.hashCode());
		result = 37
				* result
				+ (getEsiPpeLookahead() == null ? 0 : this.getEsiPpeLookahead()
						.hashCode());
		result = 37
				* result
				+ (getEsiPullLookahead() == null ? 0 : this
						.getEsiPullLookahead().hashCode());
		result = 37
				* result
				+ (getEsiAppeItemCount() == null ? 0 : this
						.getEsiAppeItemCount().hashCode());
		result = 37
				* result
				+ (getEsiGasItemCount() == null ? 0 : this.getEsiGasItemCount()
						.hashCode());
		result = 37
				* result
				+ (getEsiEliftItemCount() == null ? 0 : this
						.getEsiEliftItemCount().hashCode());
		result = 37
				* result
				+ (getEsiElecItemCount() == null ? 0 : this
						.getEsiElecItemCount().hashCode());
		result = 37
				* result
				+ (getEsiClimbItemCount() == null ? 0 : this
						.getEsiClimbItemCount().hashCode());
		result = 37
				* result
				+ (getEsiMechItemCount() == null ? 0 : this
						.getEsiMechItemCount().hashCode());
		result = 37
				* result
				+ (getEsiOtmItemCount() == null ? 0 : this.getEsiOtmItemCount()
						.hashCode());
		result = 37
				* result
				+ (getEsiPpeItemCount() == null ? 0 : this.getEsiPpeItemCount()
						.hashCode());
		result = 37
				* result
				+ (getEsiPullItemCount() == null ? 0 : this
						.getEsiPullItemCount().hashCode());
		result = 37
				* result
				+ (getEsiMsoEmailSent() == null ? 0 : this.getEsiMsoEmailSent()
						.hashCode());
		result = 37
				* result
				+ (getEsiCompletedDate() == null ? 0 : this
						.getEsiCompletedDate().hashCode());
		return result;
	}

}
