package com.bt.nat.engineer;

// default package
// Generated 18-Feb-2014 11:13:07 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * TEsitestEngineerPostcodeId generated by hbm2java
 */
@Entity
@Table(name = "t_esitest_engineer_postcode")
@NamedQuery(name = TEsitestEngineerPostcode.FIND_BY_EIN, query = "select a from TEsitestEngineerPostcode a where a.teeEngineerEin = :ein")
public class TEsitestEngineerPostcode implements java.io.Serializable {

	public static final String FIND_BY_EIN = "TEsitestEngineerPostcode.findByEin";

	private int teeId;
	private Integer teeEngineerEin;

	private TEsitestPostcodes teePostcode;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tee_epo_id")
	public TEsitestPostcodes getTeePostcode() {
		return teePostcode;
	}

	public void setTeePostcode(TEsitestPostcodes teiMaster) {
		this.teePostcode = teiMaster;
	}

	public TEsitestEngineerPostcode() {
	}

	public TEsitestEngineerPostcode(int teeId) {
		this.teeId = teeId;
	}

	public TEsitestEngineerPostcode(int teeId, Integer teeEngineerEin) {
		this.teeId = teeId;
		this.teeEngineerEin = teeEngineerEin;
	}

	@Id
	@Column(name = "tee_id", nullable = false)
	public int getTeeId() {
		return this.teeId;
	}

	public void setTeeId(int teeId) {
		this.teeId = teeId;
	}

	@Column(name = "tee_engineer_ein")
	public Integer getTeeEngineerEin() {
		return this.teeEngineerEin;
	}

	public void setTeeEngineerEin(Integer teeEngineerEin) {
		this.teeEngineerEin = teeEngineerEin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TEsitestEngineerPostcode))
			return false;
		TEsitestEngineerPostcode castOther = (TEsitestEngineerPostcode) other;

		return (this.getTeeId() == castOther.getTeeId())
				&& ((this.getTeeEngineerEin() == castOther.getTeeEngineerEin()) || (this
						.getTeeEngineerEin() != null
						&& castOther.getTeeEngineerEin() != null && this
						.getTeeEngineerEin().equals(
								castOther.getTeeEngineerEin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTeeId();
		result = 37
				* result
				+ (getTeeEngineerEin() == null ? 0 : this.getTeeEngineerEin()
						.hashCode());

		return result;
	}

}
