package com.bt.nat.account;
// default package
// Generated 14-Feb-2014 15:30:39 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * TEsitestWebGatekeeperUsers generated by hbm2java
 */
@Entity
@Table(name = "t_esitest_web_gatekeeper_users")
@NamedQuery(name = TEsitestWebGatekeeperUsers.FIND_BY_EIN, query = "select a from TEsitestWebGatekeeperUsers a where a.wguEin = :ein")
public class TEsitestWebGatekeeperUsers implements java.io.Serializable {
	
	public static final String FIND_BY_EIN = "TEsitestWebGatekeeperUsers.findByEin";

	private int wguId;
	private String wguGatekeeperPassword;
	private Date wguGatekeeperUpdate;
	private String wguGatekeeperAccountStatus;
	private Date wguGatekeeperExpiresDate;
	private Date wguLastlogon;
	private String wguProfileName;
	private Integer wguEin;
	private Integer wguManagerEin;
	private Character wguInits;
	private String wguFirstname;
	private String wguSurname;
	private String wguOuc;
	private String wguPostcode;
	private String wguTown;
	private String wguPhone;
	private String wguMobile;
	private String wguEmailId;
	private Date wguCreateTimestamp;
	private Character wguIsActive;
	private Date wguTouchDate;
	

	public TEsitestWebGatekeeperUsers() {
	}

	public TEsitestWebGatekeeperUsers(int wguId) {
		this.wguId = wguId;
	}

	public TEsitestWebGatekeeperUsers(int wguId,
			String wguGatekeeperPassword, Date wguGatekeeperUpdate,
			String wguGatekeeperAccountStatus, Date wguGatekeeperExpiresDate,
			Date wguLastlogon, String wguProfileName, Integer wguEin,
			Integer wguManagerEin, Character wguInits, String wguFirstname,
			String wguSurname, String wguOuc, String wguPostcode,
			String wguTown, String wguPhone, String wguMobile,
			String wguEmailId, Date wguCreateTimestamp, Character wguIsActive,
			Date wguTouchDate) {
		this.wguId = wguId;
		this.wguGatekeeperPassword = wguGatekeeperPassword;
		this.wguGatekeeperUpdate = wguGatekeeperUpdate;
		this.wguGatekeeperAccountStatus = wguGatekeeperAccountStatus;
		this.wguGatekeeperExpiresDate = wguGatekeeperExpiresDate;
		this.wguLastlogon = wguLastlogon;
		this.wguProfileName = wguProfileName;
		this.wguEin = wguEin;
		this.wguManagerEin = wguManagerEin;
		this.wguInits = wguInits;
		this.wguFirstname = wguFirstname;
		this.wguSurname = wguSurname;
		this.wguOuc = wguOuc;
		this.wguPostcode = wguPostcode;
		this.wguTown = wguTown;
		this.wguPhone = wguPhone;
		this.wguMobile = wguMobile;
		this.wguEmailId = wguEmailId;
		this.wguCreateTimestamp = wguCreateTimestamp;
		this.wguIsActive = wguIsActive;
		this.wguTouchDate = wguTouchDate;
		
	}

	@Id
	@Column(name = "wgu_id",  unique = true, nullable = false)
	public int getWguId() {
		return this.wguId;
	}

	public void setWguId(int wguId) {
		this.wguId = wguId;
	}

	@Column(name = "wgu_gatekeeper_password", length = 50)
	public String getWguGatekeeperPassword() {
		return this.wguGatekeeperPassword;
	}

	public void setWguGatekeeperPassword(String wguGatekeeperPassword) {
		this.wguGatekeeperPassword = wguGatekeeperPassword;
	}

	@Column(name = "wgu_gatekeeper_update", length = 23)
	public Date getWguGatekeeperUpdate() {
		return this.wguGatekeeperUpdate;
	}

	public void setWguGatekeeperUpdate(Date wguGatekeeperUpdate) {
		this.wguGatekeeperUpdate = wguGatekeeperUpdate;
	}

	@Column(name = "wgu_gatekeeper_account_status", length = 10)
	public String getWguGatekeeperAccountStatus() {
		return this.wguGatekeeperAccountStatus;
	}

	public void setWguGatekeeperAccountStatus(String wguGatekeeperAccountStatus) {
		this.wguGatekeeperAccountStatus = wguGatekeeperAccountStatus;
	}

	@Column(name = "wgu_gatekeeper_expires_date", length = 23)
	public Date getWguGatekeeperExpiresDate() {
		return this.wguGatekeeperExpiresDate;
	}

	public void setWguGatekeeperExpiresDate(Date wguGatekeeperExpiresDate) {
		this.wguGatekeeperExpiresDate = wguGatekeeperExpiresDate;
	}

	@Column(name = "wgu_lastlogon", length = 23)
	public Date getWguLastlogon() {
		return this.wguLastlogon;
	}

	public void setWguLastlogon(Date wguLastlogon) {
		this.wguLastlogon = wguLastlogon;
	}

	@Column(name = "wgu_profile_name", length = 20)
	public String getWguProfileName() {
		return this.wguProfileName;
	}

	public void setWguProfileName(String wguProfileName) {
		this.wguProfileName = wguProfileName;
	}

	@Column(name = "wgu_ein")
	public Integer getWguEin() {
		return this.wguEin;
	}

	public void setWguEin(Integer wguEin) {
		this.wguEin = wguEin;
	}

	@Column(name = "wgu_manager_ein")
	public Integer getWguManagerEin() {
		return this.wguManagerEin;
	}

	public void setWguManagerEin(Integer wguManagerEin) {
		this.wguManagerEin = wguManagerEin;
	}

	@Column(name = "wgu_inits", length = 2)
	public Character getWguInits() {
		return this.wguInits;
	}

	public void setWguInits(Character wguInits) {
		this.wguInits = wguInits;
	}

	@Column(name = "wgu_firstname", length = 30)
	public String getWguFirstname() {
		return this.wguFirstname;
	}

	public void setWguFirstname(String wguFirstname) {
		this.wguFirstname = wguFirstname;
	}

	@Column(name = "wgu_surname", length = 30)
	public String getWguSurname() {
		return this.wguSurname;
	}

	public void setWguSurname(String wguSurname) {
		this.wguSurname = wguSurname;
	}

	@Column(name = "wgu_ouc", length = 10)
	public String getWguOuc() {
		return this.wguOuc;
	}

	public void setWguOuc(String wguOuc) {
		this.wguOuc = wguOuc;
	}

	@Column(name = "wgu_postcode", length = 10)
	public String getWguPostcode() {
		return this.wguPostcode;
	}

	public void setWguPostcode(String wguPostcode) {
		this.wguPostcode = wguPostcode;
	}

	@Column(name = "wgu_town", length = 50)
	public String getWguTown() {
		return this.wguTown;
	}

	public void setWguTown(String wguTown) {
		this.wguTown = wguTown;
	}

	@Column(name = "wgu_phone", length = 50)
	public String getWguPhone() {
		return this.wguPhone;
	}

	public void setWguPhone(String wguPhone) {
		this.wguPhone = wguPhone;
	}

	@Column(name = "wgu_mobile", length = 50)
	public String getWguMobile() {
		return this.wguMobile;
	}

	public void setWguMobile(String wguMobile) {
		this.wguMobile = wguMobile;
	}

	@Column(name = "wgu_email_id", length = 100)
	public String getWguEmailId() {
		return this.wguEmailId;
	}

	public void setWguEmailId(String wguEmailId) {
		this.wguEmailId = wguEmailId;
	}

	@Column(name = "wgu_create_timestamp", length = 23)
	public Date getWguCreateTimestamp() {
		return this.wguCreateTimestamp;
	}

	public void setWguCreateTimestamp(Date wguCreateTimestamp) {
		this.wguCreateTimestamp = wguCreateTimestamp;
	}

	@Column(name = "wgu_is_active", length = 1)
	public Character getWguIsActive() {
		return this.wguIsActive;
	}

	public void setWguIsActive(Character wguIsActive) {
		this.wguIsActive = wguIsActive;
	}

	@Column(name = "wgu_touch_date", length = 23)
	public Date getWguTouchDate() {
		return this.wguTouchDate;
	}

	public void setWguTouchDate(Date wguTouchDate) {
		this.wguTouchDate = wguTouchDate;
	}



	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TEsitestWebGatekeeperUsers))
			return false;
		TEsitestWebGatekeeperUsers castOther = (TEsitestWebGatekeeperUsers) other;

		return (this.getWguId() == castOther.getWguId())
				&& ((this.getWguGatekeeperPassword() == castOther
						.getWguGatekeeperPassword()) || (this
						.getWguGatekeeperPassword() != null
						&& castOther.getWguGatekeeperPassword() != null && this
						.getWguGatekeeperPassword().equals(
								castOther.getWguGatekeeperPassword())))
				&& ((this.getWguGatekeeperUpdate() == castOther
						.getWguGatekeeperUpdate()) || (this
						.getWguGatekeeperUpdate() != null
						&& castOther.getWguGatekeeperUpdate() != null && this
						.getWguGatekeeperUpdate().equals(
								castOther.getWguGatekeeperUpdate())))
				&& ((this.getWguGatekeeperAccountStatus() == castOther
						.getWguGatekeeperAccountStatus()) || (this
						.getWguGatekeeperAccountStatus() != null
						&& castOther.getWguGatekeeperAccountStatus() != null && this
						.getWguGatekeeperAccountStatus().equals(
								castOther.getWguGatekeeperAccountStatus())))
				&& ((this.getWguGatekeeperExpiresDate() == castOther
						.getWguGatekeeperExpiresDate()) || (this
						.getWguGatekeeperExpiresDate() != null
						&& castOther.getWguGatekeeperExpiresDate() != null && this
						.getWguGatekeeperExpiresDate().equals(
								castOther.getWguGatekeeperExpiresDate())))
				&& ((this.getWguLastlogon() == castOther.getWguLastlogon()) || (this
						.getWguLastlogon() != null
						&& castOther.getWguLastlogon() != null && this
						.getWguLastlogon().equals(castOther.getWguLastlogon())))
				&& ((this.getWguProfileName() == castOther.getWguProfileName()) || (this
						.getWguProfileName() != null
						&& castOther.getWguProfileName() != null && this
						.getWguProfileName().equals(
								castOther.getWguProfileName())))
				&& ((this.getWguEin() == castOther.getWguEin()) || (this
						.getWguEin() != null && castOther.getWguEin() != null && this
						.getWguEin().equals(castOther.getWguEin())))
				&& ((this.getWguManagerEin() == castOther.getWguManagerEin()) || (this
						.getWguManagerEin() != null
						&& castOther.getWguManagerEin() != null && this
						.getWguManagerEin()
						.equals(castOther.getWguManagerEin())))
				&& ((this.getWguInits() == castOther.getWguInits()) || (this
						.getWguInits() != null
						&& castOther.getWguInits() != null && this
						.getWguInits().equals(castOther.getWguInits())))
				&& ((this.getWguFirstname() == castOther.getWguFirstname()) || (this
						.getWguFirstname() != null
						&& castOther.getWguFirstname() != null && this
						.getWguFirstname().equals(castOther.getWguFirstname())))
				&& ((this.getWguSurname() == castOther.getWguSurname()) || (this
						.getWguSurname() != null
						&& castOther.getWguSurname() != null && this
						.getWguSurname().equals(castOther.getWguSurname())))
				&& ((this.getWguOuc() == castOther.getWguOuc()) || (this
						.getWguOuc() != null && castOther.getWguOuc() != null && this
						.getWguOuc().equals(castOther.getWguOuc())))
				&& ((this.getWguPostcode() == castOther.getWguPostcode()) || (this
						.getWguPostcode() != null
						&& castOther.getWguPostcode() != null && this
						.getWguPostcode().equals(castOther.getWguPostcode())))
				&& ((this.getWguTown() == castOther.getWguTown()) || (this
						.getWguTown() != null && castOther.getWguTown() != null && this
						.getWguTown().equals(castOther.getWguTown())))
				&& ((this.getWguPhone() == castOther.getWguPhone()) || (this
						.getWguPhone() != null
						&& castOther.getWguPhone() != null && this
						.getWguPhone().equals(castOther.getWguPhone())))
				&& ((this.getWguMobile() == castOther.getWguMobile()) || (this
						.getWguMobile() != null
						&& castOther.getWguMobile() != null && this
						.getWguMobile().equals(castOther.getWguMobile())))
				&& ((this.getWguEmailId() == castOther.getWguEmailId()) || (this
						.getWguEmailId() != null
						&& castOther.getWguEmailId() != null && this
						.getWguEmailId().equals(castOther.getWguEmailId())))
				&& ((this.getWguCreateTimestamp() == castOther
						.getWguCreateTimestamp()) || (this
						.getWguCreateTimestamp() != null
						&& castOther.getWguCreateTimestamp() != null && this
						.getWguCreateTimestamp().equals(
								castOther.getWguCreateTimestamp())))
				&& ((this.getWguIsActive() == castOther.getWguIsActive()) || (this
						.getWguIsActive() != null
						&& castOther.getWguIsActive() != null && this
						.getWguIsActive().equals(castOther.getWguIsActive())))
				&& ((this.getWguTouchDate() == castOther.getWguTouchDate()) || (this
						.getWguTouchDate() != null
						&& castOther.getWguTouchDate() != null && this
						.getWguTouchDate().equals(castOther.getWguTouchDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getWguId();
		result = 37
				* result
				+ (getWguGatekeeperPassword() == null ? 0 : this
						.getWguGatekeeperPassword().hashCode());
		result = 37
				* result
				+ (getWguGatekeeperUpdate() == null ? 0 : this
						.getWguGatekeeperUpdate().hashCode());
		result = 37
				* result
				+ (getWguGatekeeperAccountStatus() == null ? 0 : this
						.getWguGatekeeperAccountStatus().hashCode());
		result = 37
				* result
				+ (getWguGatekeeperExpiresDate() == null ? 0 : this
						.getWguGatekeeperExpiresDate().hashCode());
		result = 37
				* result
				+ (getWguLastlogon() == null ? 0 : this.getWguLastlogon()
						.hashCode());
		result = 37
				* result
				+ (getWguProfileName() == null ? 0 : this.getWguProfileName()
						.hashCode());
		result = 37 * result
				+ (getWguEin() == null ? 0 : this.getWguEin().hashCode());
		result = 37
				* result
				+ (getWguManagerEin() == null ? 0 : this.getWguManagerEin()
						.hashCode());
		result = 37 * result
				+ (getWguInits() == null ? 0 : this.getWguInits().hashCode());
		result = 37
				* result
				+ (getWguFirstname() == null ? 0 : this.getWguFirstname()
						.hashCode());
		result = 37
				* result
				+ (getWguSurname() == null ? 0 : this.getWguSurname()
						.hashCode());
		result = 37 * result
				+ (getWguOuc() == null ? 0 : this.getWguOuc().hashCode());
		result = 37
				* result
				+ (getWguPostcode() == null ? 0 : this.getWguPostcode()
						.hashCode());
		result = 37 * result
				+ (getWguTown() == null ? 0 : this.getWguTown().hashCode());
		result = 37 * result
				+ (getWguPhone() == null ? 0 : this.getWguPhone().hashCode());
		result = 37 * result
				+ (getWguMobile() == null ? 0 : this.getWguMobile().hashCode());
		result = 37
				* result
				+ (getWguEmailId() == null ? 0 : this.getWguEmailId()
						.hashCode());
		result = 37
				* result
				+ (getWguCreateTimestamp() == null ? 0 : this
						.getWguCreateTimestamp().hashCode());
		result = 37
				* result
				+ (getWguIsActive() == null ? 0 : this.getWguIsActive()
						.hashCode());
		result = 37
				* result
				+ (getWguTouchDate() == null ? 0 : this.getWguTouchDate()
						.hashCode());
		
		return result;
	}

}
